backend:
  name: git-gateway
  branch: main
  repo: MrLuka118/repo1

media_folder: "photos"
public_folder: "/photos"

collections:
  - name: "portraits"
    label: "Portraits"
    folder: "photos/Portret"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string", required: false }
      - { label: "Image", name: "image", widget: "image" }

  - name: "cars"
    label: "Cars"
    folder: "photos/car"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string", required: false }
      - { label: "Image", name: "image", widget: "image" }

  - name: "landscape"
    label: "Landscape"
    folder: "photos/lendscape"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string", required: false }
      - { label: "Image", name: "image", widget: "image" }

  - name: "street"
    label: "Street"
    folder: "photos/street"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string", required: false }
      - { label: "Image", name: "image", widget: "image" }

  - name: "events"
    label: "Events"
    folder: "photos/Koncert"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string", required: false }
      - { label: "Image", name: "image", widget: "image" }
